language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - NO_RUSTUP=1

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

before_script:
  - ./scripts/travis/before_script.sh

script:
  - ./scripts/travis/script.sh
