on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.44.0", "stable"]
    steps:
      - name: "Install dependencies"
        run: sudo apt-get install libncurses5-dev
      - uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: "Install cargo-make"
        run: cargo install cargo-make
      - name: "Format"
        run: cargo make fmt
      - name: "Check"
        run: cargo make check
      - name: "Test"
        run: cargo make test
        env:
          RUST_BACKTRACE: full
      - name: "Clippy"
        run: cargo make clippy
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust: ["1.44.0", "stable"]
    steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@v1
      - name: "Install cargo-make"
        run: cargo install cargo-make
      - name: "Format"
        run: cargo make fmt
      - name: "Check"
        run: cargo make check
      - name: "Test"
        run: cargo make test
        env:
          RUST_BACKTRACE: full
      - name: "Clippy"
        run: cargo make clippy
